targets:
  $default:
    builders:
      action_box_generator|action_config_builder:
        enabled: true
      action_box_generator|action_builder:
        enabled: true

builders:
  action_builder:
    import: "package:action_box_generator/builder.dart"
    builder_factories: ["actionBuilder"]
    build_extensions: { ".dart": [".g.json"] }
    auto_apply: dependents
    runs_before: ["action_box_generator|action_config_builder"]
    build_to: cache
  action_config_builder:
    import: "package:action_box_generator/builder.dart"
    builder_factories: ["actionConfigBuilder"]
    build_extensions: { ".dart": [".a.b.dart"] }
    auto_apply: dependents
    build_to: source
