name: action_box_generator
description: Generate boilerplate code for using action_box package.
version: 0.0.27
homepage: https://github.com/yookjy/action_box_generator

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
#   path: ^1.8.0
  build: ^2.3.0
  source_gen: ^1.2.2
  analyzer: ^4.0.0
  code_builder: ^4.1.0
  dart_style: ^2.2.3
  glob: ^2.0.2
  action_box: ^0.0.48

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
  build_config: ^1.0.0
  build_runner: ^2.1.2
