name: action_box_generator
description: Generate boilerplate code for using action_box package.
version: 0.0.29
homepage: https://github.com/yookjy/action_box_generator

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  build: ^2.3.0
  source_gen: ^1.2.2
  analyzer: ^4.0.0
  code_builder: ^4.1.0
  dart_style: ^2.2.3
  glob: ^2.0.2
  action_box: ^0.0.49

dev_dependencies:
  lints: ^1.0.1
  test: ^1.21.1
  build_config: ^1.0.0
  build_runner: ^2.1.10
