name: action_box_generator
description: A starting point for Dart libraries or applications.
version: 0.0.3
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
#   path: ^1.8.0
  build: ^2.1.0
  source_gen: ^1.1.0
  analyzer: ^2.2.0
  rxdart: ^0.27.0 #Apache 2.0
  code_builder: ^4.1.0
  dart_style: ^2.0.3
  glob: ^2.0.1
  action_box:
    git:
     url: https://github.com/yookjy/action_box.git

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
  build_config: ^1.0.0
  build_runner: ^2.1.2
